### user/param
GET http://localhost:8080/day0928_spring_mvc_war/user/param?name=hjf&password=secret
Accept: application/json

### user/param-not-match
GET http://localhost:8080/day0928_spring_mvc_war/user/param-not-match?userName=hjf&password=secret
Accept: application/json

### user/param-pojo
GET http://localhost:8080/day0928_spring_mvc_war/user/param-pojo?name=hjf&password=secret
Accept: application/json

### user/body-pojo
GET http://localhost:8080/day0928_spring_mvc_war/user/body-pojo
Content-Type: application/json

{
  "name" : "Bob",
  "password": "secret"
}


### user/date-time-format
GET http://localhost:8080/day0928_spring_mvc_war/user/date-time-format?date=1234-12-14&date2=2023/09/30 09:50:32
Content-Type: application/json

### response/page
GET http://localhost:8080/day0928_spring_mvc_war/response/page
Content-Type: application/json